name = "sub"
main = "_worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间配置
[[kv_namespaces]]
binding = "SUBLINK_KV"
id = "ba96accf3e9b45aca7445d173478315e"

[[kv_namespaces]]
binding = "TEMPLATE_CONFIG"
id = "a4ad7466a262477d8acb9b1fcd9c205d"

# 访问密码在 Cloudflare Dashboard 中配置，不要在这里写明文密码！
