name = "sub"
main = "_worker.js"
compatibility_date = "2024-01-01"

# KV 命名空间配置
[[kv_namespaces]]
binding = "SUBLINK_KV"
id = "your-kv-namespace-id-here"

[[kv_namespaces]]
binding = "TEMPLATE_CONFIG"
id = "your-template-kv-namespace-id-here"

# 环境变量配置
[vars]
DEFAULT_TEMPLATE_URL = "https://raw.githubusercontent.com/juewuy/ShellCrash/refs/heads/dev/rules/ShellClash_Nano.ini"

# 访问密码在 Cloudflare Dashboard 中配置，不要在这里写明文密码！
